//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_GradingDetail
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int MarkRangeFrom { get; set; }
        public int MarkRangeTo { get; set; }
        public string GradingSchemeId { get; set; }
        public string Grade { get; set; }
        public string GradeDescription { get; set; }
        public int GradingPoint { get; set; }
        public string PassFail { get; set; }
        public bool IncludeInGPA { get; set; }
        public bool PrintOnTranscript { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    }
}
