//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_SubjectManagement
    {
        public long Id { get; set; }
        public long Code { get; set; }
        public string Name { get; set; }
        public long ProgrammeId { get; set; }
        public long IntakeId { get; set; }
        public string StudyIntake { get; set; }
        public string SemesterAcademic { get; set; }
        public string SubjectType { get; set; }
        public long AssessmentId { get; set; }
        public long GradingId { get; set; }
        public long PreRequisiteSubjectId { get; set; }
        public int CreditPoint { get; set; }
        public string AutoRegister { get; set; }
        public bool ExcludeGPACGPA { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int LocalStudentCharges { get; set; }
        public int LocalStudentResit { get; set; }
        public int LocalStudentRepeat { get; set; }
        public int LocalStudentRegrade { get; set; }
        public int InternationalStudentCharges { get; set; }
        public int InternationalStudentResit { get; set; }
        public int InternationalStudentRepeat { get; set; }
        public int InternationalStudentRegrade { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
