//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_Semester
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public long StudySemesterId { get; set; }
        public int SemesterAcademic { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AcademicYear { get; set; }
        public string AcademicSession { get; set; }
        public System.DateTime StartAddSubjectDate { get; set; }
        public System.DateTime EndAddSubjectDate { get; set; }
        public System.DateTime StartDropSubjectDate { get; set; }
        public System.DateTime EndDropSubjectDate { get; set; }
        public byte SemesterStatusEnumId { get; set; }
        public long CampusId { get; set; }
        public string Remarks { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Academic_StudySemester Academic_StudySemester { get; set; }
        public virtual General_Campus General_Campus { get; set; }
    }
}
