//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_Programme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Academic_Programme()
        {
            this.Academic_AssignAdminstratorForApplicants = new HashSet<Academic_AssignAdminstratorForApplicants>();
            this.Academic_ProgrammeStatutory = new HashSet<Academic_ProgrammeStatutory>();
            this.Academic_StudyIntake = new HashSet<Academic_StudyIntake>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public long DepartmentId { get; set; }
        public long ProgrammeTypeId { get; set; }
        public byte DurationInYear { get; set; }
        public byte NumberOfSemester { get; set; }
        public string GLCode { get; set; }
        public string MQACode { get; set; }
        public System.DateTime MQAExpiryDate { get; set; }
        public int MaxYearsToComplete { get; set; }
        public bool IsBestLastResult { get; set; }
        public string Remarks { get; set; }
        public long CampusId { get; set; }
        public long ProgrammeFeeId { get; set; }
        public long StatutoryId { get; set; }
        public System.DateTime StatutoryExpiryDate { get; set; }
        public long StudyMode { get; set; }
        public bool IsActive { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic_AssignAdminstratorForApplicants> Academic_AssignAdminstratorForApplicants { get; set; }
        public virtual General_Department General_Department { get; set; }
        public virtual Academic_ProgrammeType Academic_ProgrammeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic_ProgrammeStatutory> Academic_ProgrammeStatutory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic_StudyIntake> Academic_StudyIntake { get; set; }
    }
}
