//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_StudentAttendance
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public long IntakeCode { get; set; }
        public long StudyIntake { get; set; }
        public string AcademicSemester { get; set; }
        public string Class { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public string Subject { get; set; }
        public decimal Session { get; set; }
        public string NationalID { get; set; }
        public string PassportNo { get; set; }
        public string Attendance { get; set; }
        public string ReasonCode { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
