//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_ProgrammeStatutory
    {
        public long Id { get; set; }
        public long ProgramId { get; set; }
        public long StatutoryId { get; set; }
        public string ApprovalCode { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsActive { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Academic_Programme Academic_Programme { get; set; }
        public virtual Academic_Statutory Academic_Statutory { get; set; }
    }
}
