//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_RawMark
    {
        public long Id { get; set; }
        public Nullable<long> ProgrammeId { get; set; }
        public long IntakeId { get; set; }
        public long StudyIntake { get; set; }
        public string AcademicSemesterNo { get; set; }
        public string LecturerName { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectCredit { get; set; }
        public string CreditPoint { get; set; }
        public long AssessmentCode { get; set; }
        public string AssessmentType { get; set; }
        public string GradingScheme { get; set; }
        public long UserId { get; set; }
        public long StudentId { get; set; }
        public int RawMarks { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
