//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_OperatingHours
    {
        public long Id { get; set; }
        public long CampusId { get; set; }
        public string DaySequence { get; set; }
        public string Day { get; set; }
        public System.DateTime ClassStartTime { get; set; }
        public System.DateTime ClassEndTime { get; set; }
        public System.DateTime Break1StartTime { get; set; }
        public System.DateTime Break1EndTime { get; set; }
        public System.DateTime Break2StartTime { get; set; }
        public System.DateTime Break2EndTime { get; set; }
        public System.DateTime Break3StartTime { get; set; }
        public System.DateTime Break3EndTime { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
