//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_AssignAdminstratorForApplicants
    {
        public long Id { get; set; }
        public int PersonInChargeRole { get; set; }
        public long PersonInChargeId { get; set; }
        public long AssignedProgrammeId { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Academic_Programme Academic_Programme { get; set; }
        public virtual UAC_Role UAC_Role { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
