//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_StudyIntake
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime IntakeStart { get; set; }
        public System.DateTime IntakeEnd { get; set; }
        public long StudyModeId { get; set; }
        public long ProgrammeId { get; set; }
        public System.DateTime OrientationDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Venue { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime LocalApplicationStartDate { get; set; }
        public System.DateTime LocalApplicationEndDate { get; set; }
        public System.DateTime InternationalApplicationStartDate { get; set; }
        public System.DateTime InternationalApplicationEndDate { get; set; }
        public bool IsActive { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Academic_Programme Academic_Programme { get; set; }
        public virtual Academic_StudyMode Academic_StudyMode { get; set; }
    }
}
