//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admission_Applicant()
        {
            this.Admission_AdmissionInfo = new HashSet<Admission_AdmissionInfo>();
            this.Admission_ApplicantApplication = new HashSet<Admission_ApplicantApplication>();
            this.Admission_ApplicantEducation = new HashSet<Admission_ApplicantEducation>();
            this.Admission_ApplicantEnglishProficiency = new HashSet<Admission_ApplicantEnglishProficiency>();
            this.Admission_ApplicantGuardian = new HashSet<Admission_ApplicantGuardian>();
            this.Admission_ApplicantMedicalTest = new HashSet<Admission_ApplicantMedicalTest>();
            this.Admission_ApplicantSupportDocument = new HashSet<Admission_ApplicantSupportDocument>();
        }
    
        public long Id { get; set; }
        public long SalutationId { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public byte IdentityTypeEnumId { get; set; }
        public string IdentityNumber { get; set; }
        public System.DateTime IdentityIssueDate { get; set; }
        public System.DateTime IdentityExpiryDate { get; set; }
        public string IdentityPhoto { get; set; }
        public byte OriginTypeEnumId { get; set; }
        public string EmailAddress { get; set; }
        public string AlternateEmail { get; set; }
        public string ContactNumber { get; set; }
        public string HomeNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public long CountryOfBirthId { get; set; }
        public long CountryId { get; set; }
        public long StateId { get; set; }
        public string Nationality { get; set; }
        public long MaritalStatusId { get; set; }
        public long GenderId { get; set; }
        public long RaceId { get; set; }
        public long ReligionId { get; set; }
        public bool IsHostelRequired { get; set; }
        public long SchoolCountryId { get; set; }
        public string School { get; set; }
        public string EmergencyContactPersonName { get; set; }
        public string EmergencyContactPersonNumber { get; set; }
        public long EmergencyContactPersonRelationshipId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string BirthCertificateNumber { get; set; }
        public byte UserStatusEnumId { get; set; }
        public string ProfilePicture { get; set; }
        public string PresentAddressLine1 { get; set; }
        public string PresentAddressLine2 { get; set; }
        public string PresentPostcode { get; set; }
        public long PresentCityId { get; set; }
        public long PresentStateId { get; set; }
        public long PresentCountryId { get; set; }
        public string PermanentAddressLine1 { get; set; }
        public string PermanentAddressLine2 { get; set; }
        public string PermanentPostcode { get; set; }
        public long PermanentCountryId { get; set; }
        public long PermanentStateId { get; set; }
        public long PermanentCityId { get; set; }
        public byte StatusEnumId { get; set; }
        public byte TypeEnumId { get; set; }
        public byte StreamEnumId { get; set; }
        public long CampusId { get; set; }
        public bool IsScholarshipNeed { get; set; }
        public bool IsSponsorshipNeed { get; set; }
        public long LeadSourceId { get; set; }
        public long PreferenceIntakeId { get; set; }
        public long PreferenceProgramId1 { get; set; }
        public long PreferenceProgramId2 { get; set; }
        public long PreferenceProgramId3 { get; set; }
        public string Reference { get; set; }
        public long CampaignId { get; set; }
        public string Remarks { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public byte FailedPasswordAttemptCount { get; set; }
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        public byte FailedPasswordAnswerAttemptCount { get; set; }
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_AdmissionInfo> Admission_AdmissionInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_ApplicantApplication> Admission_ApplicantApplication { get; set; }
        public virtual Admission_Applicant Admission_Applicant1 { get; set; }
        public virtual Admission_Applicant Admission_Applicant2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_ApplicantEducation> Admission_ApplicantEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_ApplicantEnglishProficiency> Admission_ApplicantEnglishProficiency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_ApplicantGuardian> Admission_ApplicantGuardian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_ApplicantMedicalTest> Admission_ApplicantMedicalTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_ApplicantSupportDocument> Admission_ApplicantSupportDocument { get; set; }
    }
}
