//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_SiteSetting
    {
        public long Id { get; set; }
        public string PageContent { get; set; }
        public string TermsName { get; set; }
        public string TermsContent { get; set; }
        public string TermsUrl { get; set; }
        public string PrivacyName { get; set; }
        public string PrivacyContent { get; set; }
        public string PrivacyUrl { get; set; }
        public string RefundName { get; set; }
        public string RefundContent { get; set; }
        public string RefundUrl { get; set; }
        public string Policy1Name { get; set; }
        public string Policy1Content { get; set; }
        public string Policy1Url { get; set; }
        public string Policy2Name { get; set; }
        public string Policy2Content { get; set; }
        public string Policy2Url { get; set; }
        public string Policy3Name { get; set; }
        public string Policy3Content { get; set; }
        public string Policy3Url { get; set; }
        public string FooterText { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public long LastUpdateById { get; set; }
        public bool IsDeleted { get; set; }
    }
}
