//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_School
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Stage { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeFax { get; set; }
        public string Email { get; set; }
        public string CityType { get; set; }
        public string GovAidType { get; set; }
        public int NumberOfStudent { get; set; }
        public int NumberOfTeacher { get; set; }
        public bool IsPreSchool { get; set; }
        public bool IsSpecialSchool { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool IsActive { get; set; }
        public string PrincipalName { get; set; }
        public int ContactNo { get; set; }
        public string Remarks { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
