//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bursary_FeeType
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public long FeeTypeCategoryId { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public string AcademicSemester { get; set; }
        public bool TaxWith { get; set; }
        public long TaxSettingId { get; set; }
        public int LocalStudent { get; set; }
        public int InternationalStudent { get; set; }
        public string Remarks { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Bursary_FeeTypeCategory Bursary_FeeTypeCategory { get; set; }
        public virtual Bursary_TaxSetting Bursary_TaxSetting { get; set; }
    }
}
