//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bursary_BankSetting
    {
        public long Id { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public int BankAcctNo { get; set; }
        public string Branch { get; set; }
        public int TelephoneNo { get; set; }
        public string PICName { get; set; }
        public int PICHpNo { get; set; }
        public bool Status { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public int Postcode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
