//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_MatricNumber
    {
        public long Id { get; set; }
        public string Sequence1 { get; set; }
        public string Sequence2 { get; set; }
        public string Sequence3 { get; set; }
        public string Sequence4 { get; set; }
        public string FixedLength { get; set; }
        public string StartWith { get; set; }
        public int CurrentRunningNumber { get; set; }
        public string UpdatePreview { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    }
}
