//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General_Department()
        {
            this.Academic_Programme = new HashSet<Academic_Programme>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int OrderNumber { get; set; }
        public string Description { get; set; }
        public byte DepartmentTypeEumId { get; set; }
        public string Website { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Address { get; set; }
        public long ContactPersonId { get; set; }
        public string ContactPersonMobileNumber { get; set; }
        public int PostCode { get; set; }
        public System.DateTime EstablishDate { get; set; }
        public long CampusId { get; set; }
        public long ParentId { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public long CreateById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic_Programme> Academic_Programme { get; set; }
        public virtual General_Campus General_Campus { get; set; }
    }
}
