//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Institute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General_Institute()
        {
            this.General_Campus = new HashSet<General_Campus>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Postcode { get; set; }
        public long CityId { get; set; }
        public long StateId { get; set; }
        public long CountryId { get; set; }
        public string OfficeNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string WebUrl { get; set; }
        public string Logo { get; set; }
        public string BackgroundImage { get; set; }
        public long ContactPersonId { get; set; }
        public string ContactPersonMobileNumber { get; set; }
        public string RankingDescription { get; set; }
        public System.DateTime EstablishDate { get; set; }
        public string Specialization { get; set; }
        public string Accreditation { get; set; }
        public string FinancialAid { get; set; }
        public string Remarks { get; set; }
        public long InstituteTypeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<General_Campus> General_Campus { get; set; }
        public virtual General_Country General_Country { get; set; }
        public virtual General_InstituteType General_InstituteType { get; set; }
    }
}
