//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_PersonnelQuestion
    {
        public long Id { get; set; }
        public string QuestionSet { get; set; }
        public string LevelOfStudy { get; set; }
        public bool Status { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastCreateDate { get; set; }
        public long LastChangedById { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
        public long AdmissionInfoId { get; set; }
    
        public virtual Admission_AdmissionInfo Admission_AdmissionInfo { get; set; }
    }
}
