//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Facility
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public long FacilityTypeId { get; set; }
        public string Image { get; set; }
        public int CapacityRegular { get; set; }
        public int CapacityExam { get; set; }
        public int LengthInFeet { get; set; }
        public int WidthInFeet { get; set; }
        public string CampusBuilding { get; set; }
        public int Floor { get; set; }
        public int RoomNumber { get; set; }
        public string InternetAccess { get; set; }
        public long PersonInChargeId { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual General_FacilityType General_FacilityType { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
