//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartCampusDBEntities : DbContext
    {
        public SmartCampusDBEntities()
            : base("name=SmartCampusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academic_AssessementDetail> Academic_AssessementDetail { get; set; }
        public virtual DbSet<Academic_Assessment> Academic_Assessment { get; set; }
        public virtual DbSet<Academic_AssignAdminstratorForApplicants> Academic_AssignAdminstratorForApplicants { get; set; }
        public virtual DbSet<Academic_Calendar> Academic_Calendar { get; set; }
        public virtual DbSet<Academic_Course> Academic_Course { get; set; }
        public virtual DbSet<Academic_EnrolStudent> Academic_EnrolStudent { get; set; }
        public virtual DbSet<Academic_EntranceSubject> Academic_EntranceSubject { get; set; }
        public virtual DbSet<Academic_ExamDocket> Academic_ExamDocket { get; set; }
        public virtual DbSet<Academic_ExamSchedule> Academic_ExamSchedule { get; set; }
        public virtual DbSet<Academic_FeeMaster> Academic_FeeMaster { get; set; }
        public virtual DbSet<Academic_GradingDetail> Academic_GradingDetail { get; set; }
        public virtual DbSet<Academic_GradingScheme> Academic_GradingScheme { get; set; }
        public virtual DbSet<Academic_Intake> Academic_Intake { get; set; }
        public virtual DbSet<Academic_ManageDiscipline> Academic_ManageDiscipline { get; set; }
        public virtual DbSet<Academic_MarkEntry> Academic_MarkEntry { get; set; }
        public virtual DbSet<Academic_OperatingHours> Academic_OperatingHours { get; set; }
        public virtual DbSet<Academic_OtherFee> Academic_OtherFee { get; set; }
        public virtual DbSet<Academic_PlacementTest> Academic_PlacementTest { get; set; }
        public virtual DbSet<Academic_PreRequisiteSubject> Academic_PreRequisiteSubject { get; set; }
        public virtual DbSet<Academic_Programme> Academic_Programme { get; set; }
        public virtual DbSet<Academic_ProgrammeStatutory> Academic_ProgrammeStatutory { get; set; }
        public virtual DbSet<Academic_ProgrammeType> Academic_ProgrammeType { get; set; }
        public virtual DbSet<Academic_RawMark> Academic_RawMark { get; set; }
        public virtual DbSet<Academic_Semester> Academic_Semester { get; set; }
        public virtual DbSet<Academic_Statutory> Academic_Statutory { get; set; }
        public virtual DbSet<Academic_StudentAttendance> Academic_StudentAttendance { get; set; }
        public virtual DbSet<Academic_StudyIntake> Academic_StudyIntake { get; set; }
        public virtual DbSet<Academic_StudyMode> Academic_StudyMode { get; set; }
        public virtual DbSet<Academic_StudySemester> Academic_StudySemester { get; set; }
        public virtual DbSet<Academic_StudyYear> Academic_StudyYear { get; set; }
        public virtual DbSet<Academic_StudyYearSemester> Academic_StudyYearSemester { get; set; }
        public virtual DbSet<Academic_Subject> Academic_Subject { get; set; }
        public virtual DbSet<Academic_SubjectManagement> Academic_SubjectManagement { get; set; }
        public virtual DbSet<Admission_AdmissionFee> Admission_AdmissionFee { get; set; }
        public virtual DbSet<Admission_AdmissionInfo> Admission_AdmissionInfo { get; set; }
        public virtual DbSet<Admission_Applicant> Admission_Applicant { get; set; }
        public virtual DbSet<Admission_Applicant_LeadSource> Admission_Applicant_LeadSource { get; set; }
        public virtual DbSet<Admission_ApplicantApplication> Admission_ApplicantApplication { get; set; }
        public virtual DbSet<Admission_ApplicantEducation> Admission_ApplicantEducation { get; set; }
        public virtual DbSet<Admission_ApplicantEducationSubject> Admission_ApplicantEducationSubject { get; set; }
        public virtual DbSet<Admission_ApplicantEnglishProficiency> Admission_ApplicantEnglishProficiency { get; set; }
        public virtual DbSet<Admission_ApplicantGuardian> Admission_ApplicantGuardian { get; set; }
        public virtual DbSet<Admission_ApplicantMedicalTest> Admission_ApplicantMedicalTest { get; set; }
        public virtual DbSet<Admission_ApplicantSupportDocument> Admission_ApplicantSupportDocument { get; set; }
        public virtual DbSet<Admission_ApplicantTimeline> Admission_ApplicantTimeline { get; set; }
        public virtual DbSet<Admission_ApplicationStatus> Admission_ApplicationStatus { get; set; }
        public virtual DbSet<Admission_Campaign> Admission_Campaign { get; set; }
        public virtual DbSet<Admission_EnglishProficiency> Admission_EnglishProficiency { get; set; }
        public virtual DbSet<Admission_Intake> Admission_Intake { get; set; }
        public virtual DbSet<Admission_KeyEvalutionIndicator> Admission_KeyEvalutionIndicator { get; set; }
        public virtual DbSet<Admission_Letters> Admission_Letters { get; set; }
        public virtual DbSet<Admission_MedicalTest> Admission_MedicalTest { get; set; }
        public virtual DbSet<Admission_ProgrammeSupportingDocument> Admission_ProgrammeSupportingDocument { get; set; }
        public virtual DbSet<Admission_School> Admission_School { get; set; }
        public virtual DbSet<Admission_SiteSetting> Admission_SiteSetting { get; set; }
        public virtual DbSet<Admission_StudyLevelSubject> Admission_StudyLevelSubject { get; set; }
        public virtual DbSet<Admission_SupportDocument> Admission_SupportDocument { get; set; }
        public virtual DbSet<Bursary_Apportionment> Bursary_Apportionment { get; set; }
        public virtual DbSet<Bursary_BankSetting> Bursary_BankSetting { get; set; }
        public virtual DbSet<Bursary_CreditHour> Bursary_CreditHour { get; set; }
        public virtual DbSet<Bursary_FeeType> Bursary_FeeType { get; set; }
        public virtual DbSet<Bursary_FeeTypeCategory> Bursary_FeeTypeCategory { get; set; }
        public virtual DbSet<Bursary_FinePolicy> Bursary_FinePolicy { get; set; }
        public virtual DbSet<Bursary_Invoice> Bursary_Invoice { get; set; }
        public virtual DbSet<Bursary_PackageDetails> Bursary_PackageDetails { get; set; }
        public virtual DbSet<Bursary_PackageSettings> Bursary_PackageSettings { get; set; }
        public virtual DbSet<Bursary_TaxSetting> Bursary_TaxSetting { get; set; }
        public virtual DbSet<General_Announcement> General_Announcement { get; set; }
        public virtual DbSet<General_Asset> General_Asset { get; set; }
        public virtual DbSet<General_Bank> General_Bank { get; set; }
        public virtual DbSet<General_CampaignVisitor> General_CampaignVisitor { get; set; }
        public virtual DbSet<General_Campus> General_Campus { get; set; }
        public virtual DbSet<General_City> General_City { get; set; }
        public virtual DbSet<General_Country> General_Country { get; set; }
        public virtual DbSet<General_DeclarationTerms> General_DeclarationTerms { get; set; }
        public virtual DbSet<General_Department> General_Department { get; set; }
        public virtual DbSet<General_EmailTemplate> General_EmailTemplate { get; set; }
        public virtual DbSet<General_Facility> General_Facility { get; set; }
        public virtual DbSet<General_FacilityType> General_FacilityType { get; set; }
        public virtual DbSet<General_Gender> General_Gender { get; set; }
        public virtual DbSet<General_GlobalSetup> General_GlobalSetup { get; set; }
        public virtual DbSet<General_GradeAchieve> General_GradeAchieve { get; set; }
        public virtual DbSet<General_HolidaySetup> General_HolidaySetup { get; set; }
        public virtual DbSet<General_IdentityType> General_IdentityType { get; set; }
        public virtual DbSet<General_IncomeRange> General_IncomeRange { get; set; }
        public virtual DbSet<General_Institute> General_Institute { get; set; }
        public virtual DbSet<General_InstituteType> General_InstituteType { get; set; }
        public virtual DbSet<General_Language> General_Language { get; set; }
        public virtual DbSet<General_LeadsEducationResult> General_LeadsEducationResult { get; set; }
        public virtual DbSet<General_Letter> General_Letter { get; set; }
        public virtual DbSet<General_LetterTemplate> General_LetterTemplate { get; set; }
        public virtual DbSet<General_LevelOfStudy> General_LevelOfStudy { get; set; }
        public virtual DbSet<General_ManageDocument> General_ManageDocument { get; set; }
        public virtual DbSet<General_ManageSystem> General_ManageSystem { get; set; }
        public virtual DbSet<General_MaritalStatus> General_MaritalStatus { get; set; }
        public virtual DbSet<General_MatricNumber> General_MatricNumber { get; set; }
        public virtual DbSet<General_OperatingHour> General_OperatingHour { get; set; }
        public virtual DbSet<General_PersonnelQuestion> General_PersonnelQuestion { get; set; }
        public virtual DbSet<General_QualificationLevel> General_QualificationLevel { get; set; }
        public virtual DbSet<General_QualificationLevelSubject> General_QualificationLevelSubject { get; set; }
        public virtual DbSet<General_Race> General_Race { get; set; }
        public virtual DbSet<General_Relationship> General_Relationship { get; set; }
        public virtual DbSet<General_Religion> General_Religion { get; set; }
        public virtual DbSet<General_Salutation> General_Salutation { get; set; }
        public virtual DbSet<General_SocialMedia> General_SocialMedia { get; set; }
        public virtual DbSet<General_State> General_State { get; set; }
        public virtual DbSet<General_StatusEmail> General_StatusEmail { get; set; }
        public virtual DbSet<General_SystemEmail> General_SystemEmail { get; set; }
        public virtual DbSet<HR_HolidayCalendar> HR_HolidayCalendar { get; set; }
        public virtual DbSet<HR_HolidayTrack> HR_HolidayTrack { get; set; }
        public virtual DbSet<UAC_HackAttempt> UAC_HackAttempt { get; set; }
        public virtual DbSet<UAC_LoginAudit> UAC_LoginAudit { get; set; }
        public virtual DbSet<UAC_PassReset> UAC_PassReset { get; set; }
        public virtual DbSet<UAC_Role> UAC_Role { get; set; }
        public virtual DbSet<UAC_RolePremissionMap> UAC_RolePremissionMap { get; set; }
        public virtual DbSet<UAC_RoleUserMap> UAC_RoleUserMap { get; set; }
        public virtual DbSet<User_Access> User_Access { get; set; }
        public virtual DbSet<User_Account> User_Account { get; set; }
        public virtual DbSet<User_ContactAddress> User_ContactAddress { get; set; }
        public virtual DbSet<User_ContactEmail> User_ContactEmail { get; set; }
        public virtual DbSet<User_ContactNumber> User_ContactNumber { get; set; }
        public virtual DbSet<User_Credential> User_Credential { get; set; }
        public virtual DbSet<User_Education> User_Education { get; set; }
        public virtual DbSet<User_Employee> User_Employee { get; set; }
        public virtual DbSet<User_Image> User_Image { get; set; }
        public virtual DbSet<General_OnlineSupport> General_OnlineSupport { get; set; }
    }
}
