//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAC_PassReset
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public long RequestById { get; set; }
        public int Code { get; set; }
        public byte ValidMins { get; set; }
        public byte TypeEnumId { get; set; }
        public byte StatusEnumId { get; set; }
        public Nullable<System.DateTime> ResetDate { get; set; }
        public Nullable<long> ResetById { get; set; }
        public string RequestIp { get; set; }
        public string ResetIp { get; set; }
        public int FailedAttemptCount { get; set; }
    }
}
