//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAC_LoginAudit
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string FromIp { get; set; }
        public string MacAddress { get; set; }
        public byte StatusEnumId { get; set; }
        public bool IsMobileBrowser { get; set; }
        public string Browser { get; set; }
    }
}
