//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_ContactNumber
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string ContactNumber { get; set; }
        public byte ContactNumberTypeEnumId { get; set; }
        public long CountryId { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
        public bool IsMailingContact { get; set; }
        public byte PrivacyEnumId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual General_Country General_Country { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
