//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_ContactAddress
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string CareOfPersonName { get; set; }
        public byte ContactAddressTypeEnumId { get; set; }
        public string AppartmentNo { get; set; }
        public string HouseNo { get; set; }
        public string RoadNo { get; set; }
        public string AreaInfo { get; set; }
        public string PostOffice { get; set; }
        public string PoliceStation { get; set; }
        public string District { get; set; }
        public Nullable<int> PostCode { get; set; }
        public long CountryId { get; set; }
        public bool IsMailingContact { get; set; }
        public bool IsValid { get; set; }
        public byte PrivacyEnumId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual General_Country General_Country { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
