//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Account()
        {
            this.Academic_AssignAdminstratorForApplicants = new HashSet<Academic_AssignAdminstratorForApplicants>();
            this.General_Facility = new HashSet<General_Facility>();
            this.UAC_RoleUserMap = new HashSet<UAC_RoleUserMap>();
            this.User_Access = new HashSet<User_Access>();
            this.User_ContactAddress = new HashSet<User_ContactAddress>();
            this.User_ContactEmail = new HashSet<User_ContactEmail>();
            this.User_ContactNumber = new HashSet<User_ContactNumber>();
            this.User_Image = new HashSet<User_Image>();
        }
    
        public long Id { get; set; }
        public string FullName { get; set; }
        public string LocalName { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PlaceOfBirthCity { get; set; }
        public Nullable<long> PlaceOfBirthCountryId { get; set; }
        public byte GenderEnumId { get; set; }
        public byte ReligionEnumId { get; set; }
        public byte MaritalStatusEnumId { get; set; }
        public byte BloodGroupEnumId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public bool IsSpouseWorking { get; set; }
        public bool HaveChildren { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> Weight { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsSpouseDisabled { get; set; }
        public bool IsLate { get; set; }
        public bool IsMilitary { get; set; }
        public string Race { get; set; }
        public string Nationality { get; set; }
        public byte ResidenceStatusEnumId { get; set; }
        public byte ResidentTypeEnumId { get; set; }
        public bool IsPermanentResident { get; set; }
        public string NationalIdNumber { get; set; }
        public string BirthCertificateNumber { get; set; }
        public byte UserTypeEnumId { get; set; }
        public byte UserStatusEnumId { get; set; }
        public Nullable<long> BankId { get; set; }
        public string BankAccountNo { get; set; }
        public byte CategoryEnumId { get; set; }
        public long CampusId { get; set; }
        public string PersonalNo { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic_AssignAdminstratorForApplicants> Academic_AssignAdminstratorForApplicants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<General_Facility> General_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAC_RoleUserMap> UAC_RoleUserMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Access> User_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ContactAddress> User_ContactAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ContactEmail> User_ContactEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ContactNumber> User_ContactNumber { get; set; }
        public virtual User_Credential User_Credential { get; set; }
        public virtual User_Employee User_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Image> User_Image { get; set; }
    }
}
