//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelerikRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Education
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public byte OrderNo { get; set; }
        public string DegreeTitle { get; set; }
        public string ConcentratedMajor { get; set; }
        public string InstitutionName { get; set; }
        public string Board { get; set; }
        public string Result { get; set; }
        public string Duration { get; set; }
        public int YearOfPassing { get; set; }
        public string Session { get; set; }
        public string Achievement { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    }
}
